ribbon:
  VipAddress: test
  ServerListRefreshInterval: 2000
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
hazelcast.network.addresses: '[''121.0.0.1:5701'']'
